/* XPM */
/*
 * Copyright 1999-2000  Martin Hock
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

static char * picDUp[] = {
"32 16 3 1",
" 	c None",
".	c #FFFFFF",
"+	c #000000",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"               ..               ",
"              .++.              ",
"             .++++.             ",
"            .++++++.            ",
"           .++++++++.           ",
"          ............          ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                "};
/* XPM */
static char * picDRight[] = {
"16 32 3 1",
" 	c None",
".	c #FFFFFF",
"+	c #000000",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"     .          ",
"     ..         ",
"     .+.        ",
"     .++.       ",
"     .+++.      ",
"     .++++.     ",
"     .++++.     ",
"     .+++.      ",
"     .++.       ",
"     .+.        ",
"     ..         ",
"     .          ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                "};
/* XPM */
static char * picDDown[] = {
"32 16 3 1",
" 	c None",
".	c #FFFFFF",
"+	c #000000",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"          ............          ",
"           .++++++++.           ",
"            .++++++.            ",
"             .++++.             ",
"              .++.              ",
"               ..               ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                "};
/* XPM */
static char * picDLeft[] = {
"16 32 3 1",
" 	c None",
".	c #FFFFFF",
"+	c #000000",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"          .     ",
"         ..     ",
"        .+.     ",
"       .++.     ",
"      .+++.     ",
"     .++++.     ",
"     .++++.     ",
"      .+++.     ",
"       .++.     ",
"        .+.     ",
"         ..     ",
"          .     ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                "};

/* XPM */
static char * picDUpW[] = {
"32 16 3 1",
" 	c None",
".	c #000000",
"+	c #FFFFFF",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"               ..               ",
"              .++.              ",
"             .++++.             ",
"            .++++++.            ",
"           .++++++++.           ",
"          ............          ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                "};
/* XPM */
static char * picDRightW[] = {
"16 32 3 1",
" 	c None",
".	c #000000",
"+	c #FFFFFF",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"     .          ",
"     ..         ",
"     .+.        ",
"     .++.       ",
"     .+++.      ",
"     .++++.     ",
"     .++++.     ",
"     .+++.      ",
"     .++.       ",
"     .+.        ",
"     ..         ",
"     .          ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                "};
/* XPM */
static char * picDDownW[] = {
"32 16 3 1",
" 	c None",
".	c #000000",
"+	c #FFFFFF",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"          ............          ",
"           .++++++++.           ",
"            .++++++.            ",
"             .++++.             ",
"              .++.              ",
"               ..               ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                "};
/* XPM */
static char * picDLeftW[] = {
"16 32 3 1",
" 	c None",
".	c #000000",
"+	c #FFFFFF",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"          .     ",
"         ..     ",
"        .+.     ",
"       .++.     ",
"      .+++.     ",
"     .++++.     ",
"     .++++.     ",
"      .+++.     ",
"       .++.     ",
"        .+.     ",
"         ..     ",
"          .     ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                "};
