#!/bin/bash
# Make marble pictures for GFingerPoken
# Copyright 2005  Bas Wijnen <shevek@fmf.nl>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

blender -b "`dirname $0`"/marbles.blend -a

montage -geometry +0+0 -tile 64x1 -compose Copy -background none `seq 1 64 | xargs printf "/tmp/%04d.png "` marbles.png

pngtopnm marbles.png | ppmtoxpm -name picMarble | sed 's/\#0E0E38386666/None/' > marblepix.h

rm marbles.png
