.TH GFPOKEN 6
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
.PP
gfpoken \- Recreate a grid of mirrors from clues
.SH SYNOPSIS
.B gfpoken
.\"  .I "[options] files ..."
.SH "DESCRIPTION"
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
Please read the author's README file for information about this program.
On Debian GNU/Linux systems, this file can be found as
/usr/share/doc/gfpoken/README .
.SH AUTHOR
This manual page was written by William Ono <wmono@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
